#+TITLE: Paper Topics 
#+SLUG: papers
#+STATUS: hidden

------

WRITE approximately 3-5 double-spaced pages on /one/ of the following
topics. For whatever topic you pick you must write it according to the
format detailed below.

The DUE DATE for the papers is: *Friday, December 2*. 

* Paper Structure

-  EXPLAIN the argument (what are the premises? what is the conclusion?).
   -  You may present the argument in numbered form if you wish, though
      if you do so be sure to show the connection between the argument
      as you've explained it and the relevant text(s).
-  ASSESS the argument for validity and soundness and /explain why/ it
   is/isn't valid/sound.
-  If there are problematic premises, then EXPLAIN how the author
   defends them.
-  Is the argument for the conclusion CONVINCING? WHY or why NOT?

For any topic you are free to draw on any concepts or readings we have
discussed thus far, but be sure to answer the questions raised by the
prompt.

I expect papers to be /clear/. Write in short and complete sentences.
Where necessary, sacrifice elegance in favor of clarity. Signpost
heavily. Avoid needless generality or autobiographical reportage. Be
sure to /appropriately cite/ any sources which you consult in the writing
of your paper. *This includes sources which you do not directly quote!*
For further questions please consult the [[file:{filename}/readings/PaperRubric.pdf][grading rubric]].

Be sure to review the linked guidelines on [[file:{filename}/readings/ThesisOverview.pdf][writing a thesis statement]] and [[file:{filename}/readings/PaperStructure.pdf][paper
structure]]!

* Paper Topics

1. In “What is it like to be a bat” Thomas Nagel argues that the nature
   of consciousness presents a challenge to our understanding of
   physicalism. What is Nagel's argument? What is the significance for
   physicalism of a “point of view” as Nagel understands it? Is Nagel's
   argument convincing? Why or why not?

2. Explain the Knowledge Argument. What problem does it present for
   physicalism? What is the basic structure of Lewis's reply? Is his
   reply convincing? Provide reasons why or why not.

3. Explain the free will problem. Why might free will and determinism be
   incompatible? What, if any reason do we have to think that they /are/
   compatible? Defend your position by providing reasons why or why not.

4. Mackie argues that there are no objective values. Explain his
   arguments. Are they convincing? Provide reasons why or why not.


